export const layoutConfig = {
  1: {
    pageLoader: true,
    subHeader: true,
    breadcrumbs: true,
    leftAside: true,
    rightAside: true,
    footer: true,
    quickSide: true,
    quickNav: true,
    scrollTop: true,
    header: true
  },
  2: {
    pageLoader: true,
    subHeader: true,
    breadcrumbs: true,
    leftAside: true,
    rightAside: true,
    footer: true,
    quickSide: true,
    quickNav: true,
    scrollTop: true,
    header: true
  },
  3: {
    pageLoader: true,
    subHeader: true,
    breadcrumbs: true,
    leftAside: true,
    rightAside: true,
    footer: true,
    quickSide: true,
    quickNav: true,
    scrollTop: true,
    header: true
  },
  4: {
    pageLoader: true,
    subHeader: true,
    breadcrumbs: true,
    leftAside: true,
    rightAside: true,
    footer: true,
    quickSide: true,
    quickNav: true,
    scrollTop: true,
    header: true
  },
  5: {
    pageLoader: true,
    subHeader: true,
    breadcrumbs: true,
    leftAside: true,
    rightAside: true,
    footer: true,
    quickSide: true,
    quickNav: true,
    scrollTop: true,
    header: true
  },
  6: {
    pageLoader: true,
    subHeader: true,
    breadcrumbs: true,
    leftAside: true,
    rightAside: true,
    footer: true,
    quickSide: true,
    quickNav: true,
    scrollTop: true,
    header: true
  },
  7: {
    wide: false, // don't allow
    pageLoader: true,
    headerFixed: true,
    headerFixedMobile: true,
    searchExpandable: true,
    subHeader: true,
    breadcrumbs: true,
    leftAside: true,
    rightAside: true,
    submenuDropdown: true,
    footer: true,
    quickSide: true,
    quickNav: true,
    scrollTop: true,
    header: true
  },
  8: {
    wide: false,
    pageLoader: true,
    headerFixed: true,
    headerFixedMobile: true,
    searchExpandable: false,
    subHeader: true,
    breadcrumbs: false,
    leftAside: true,
    rightAside: true,
    submenuDropdown: false,
    footer: true,
    quickSide: true,
    quickNav: true,
    scrollTop: true,
    header: true
  },
  9: {
    pageLoader: true,
    subHeader: true,
    breadcrumbs: true,
    leftAside: true,
    rightAside: true,
    footer: true,
    quickSide: true,
    quickNav: true,
    scrollTop: true,
    header: true
  },
  10: {
    pageLoader: true,
    subHeader: true,
    breadcrumbs: true,
    leftAside: true,
    rightAside: true,
    footer: true,
    quickSide: true,
    quickNav: true,
    scrollTop: true,
    header: true
  },
  11: {
    pageLoader: true,
    subHeader: true,
    breadcrumbs: true,
    leftAside: true,
    rightAside: true,
    footer: true,
    quickSide: true,
    quickNav: true,
    scrollTop: true,
    header: true
  },
  12: {
    pageLoader: true,
    subHeader: true,
    breadcrumbs: true,
    leftAside: true,
    rightAside: true,
    footer: true,
    quickSide: true,
    quickNav: true,
    scrollTop: true,
    header: true
  }
};
